### ISSUE TITLE
Duvida no Integrador

### ISSUE THREAD

**Issue by adrbarros** [ACBrNet/ACBr.Net.Integrador#5]
Fazendo alguns testes aqui, percebi que a Classe Resposta não esta sendo preenchida com o Retorno de XML

IdPagamento no Caso esta NULL
![IntegradorCE01](https://user-images.githubusercontent.com/15065213/125347629-89d0d780-e331-11eb-89ed-9ed4103c07ed.png)

e o retorno RESPOSTA.XML, esta com esse conteudo
![IntegradorCE02](https://user-images.githubusercontent.com/15065213/125347744-acfb8700-e331-11eb-846c-bcac6c0a5064.png)

é assim mesmo, ou deveria estar sendo Preenchida a Respota?

**Comment by rftd** [comment]
Rapaz nem sei como funciona isso quem implementou isso foi um contribuidor o @marcosgerene

**Comment by adrbarros** [comment]
Obrigado pelo Retorno

**Comment by marcosgerene** [comment]
@adrbarros você tem meu contato pessoal , depois me chama la pra eu entender melhor

**Comment by khaddmussistemas** [comment]
Teve alguma solução nesse caso o meu tbm está assim;

**Comment by marcosgerene** [comment]
Atualizei depois de muito tempo meu integrador e tive o mesmo problema que vocês, vou tentar entender o motivo
